packages:
  - Chapter02/*
  - Chapter03/*
  - Chapter04/*
  - Chapter05/*
  - Chapter06/*
  - Chapter07/*
  - Chapter08/*
  - Chapter09/*
  - Chapter10/*
  - Chapter11/*
  - Chapter12/*
  - Chapter13/*
  - Chapter14/*
  - Chapter15/*
  - Chapter16/*
  - Chapter17/*
  - Chapter18/*
  - Chapter19/*
  - Chapter20/*
  - Chapter21/*

onlyBuiltDependencies:
  - sqlite3
